# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r: release
cache: packages
sudo: required
dist: xenial

before_install:
  - sudo apt-get install ghostscript
  - sudo apt-get install libgsl-dev

r_build_args: --compact-vignettes=gs+qpdf --no-build-vignettes
r_check_args: --compact-vignettes=gs+qpdf --no-build-vignettes

after_failure: "cat /home/travis/build/boennecd/dynamichazard/dynamichazard.Rcheck/00install.out"
