--
-- Create a table where the column names exactly match
-- the column names in the published 2013 CSV files.
--
CREATE TABLE drive_stats (
    date TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    model TEXT NOT NULL,
    capacity_bytes INTEGER (8) NOT NULL,
    failure INTEGER (1) NOT NULL,
--    smart_1_normalized INTEGER,
    smart_1_raw INTEGER,
--    smart_2_normalized INTEGER,
    smart_2_raw INTEGER,
--    smart_3_normalized INTEGER,
    smart_3_raw INTEGER,
--    smart_4_normalized INTEGER,
    smart_4_raw INTEGER,
--    smart_5_normalized INTEGER,
    smart_5_raw INTEGER,
--    smart_7_normalized INTEGER,
    smart_7_raw INTEGER,
--    smart_8_normalized INTEGER,
    smart_8_raw INTEGER,
--    smart_9_normalized INTEGER,
    smart_9_raw INTEGER,
--    smart_10_normalized INTEGER,
    smart_10_raw INTEGER,
--    smart_11_normalized INTEGER,
    smart_11_raw INTEGER,
--    smart_12_normalized INTEGER,
    smart_12_raw INTEGER,
--    smart_13_normalized INTEGER,
    smart_13_raw INTEGER,
--    smart_15_normalized INTEGER,
    smart_15_raw INTEGER,
--    smart_183_normalized INTEGER,
    smart_183_raw INTEGER,
--    smart_184_normalized INTEGER,
    smart_184_raw INTEGER,
--    smart_187_normalized INTEGER,
    smart_187_raw INTEGER,
--    smart_188_normalized INTEGER,
    smart_188_raw INTEGER,
--    smart_189_normalized INTEGER,
    smart_189_raw INTEGER,
--    smart_190_normalized INTEGER,
    smart_190_raw INTEGER,
--    smart_191_normalized INTEGER,
    smart_191_raw INTEGER,
--    smart_192_normalized INTEGER,
    smart_192_raw INTEGER,
--    smart_193_normalized INTEGER,
    smart_193_raw INTEGER,
--    smart_194_normalized INTEGER,
    smart_194_raw INTEGER,
--    smart_195_normalized INTEGER,
    smart_195_raw INTEGER,
--    smart_196_normalized INTEGER,
    smart_196_raw INTEGER,
--    smart_197_normalized INTEGER,
    smart_197_raw INTEGER,
--    smart_198_normalized INTEGER,
    smart_198_raw INTEGER,
--    smart_199_normalized INTEGER,
    smart_199_raw INTEGER,
--    smart_200_normalized INTEGER,
    smart_200_raw INTEGER,
--    smart_201_normalized INTEGER,
    smart_201_raw INTEGER,
--    smart_223_normalized INTEGER,
    smart_223_raw INTEGER,
--    smart_225_normalized INTEGER,
    smart_225_raw INTEGER,
--    smart_240_normalized INTEGER,
    smart_240_raw INTEGER,
--    smart_241_normalized INTEGER,
    smart_241_raw INTEGER,
--    smart_242_normalized INTEGER,
    smart_242_raw INTEGER,
--    smart_250_normalized INTEGER,
    smart_250_raw INTEGER,
--    smart_251_normalized INTEGER,
    smart_251_raw INTEGER,
--    smart_252_normalized INTEGER,
    smart_252_raw INTEGER,
--    smart_254_normalized INTEGER,
    smart_254_raw INTEGER,
--    smart_255_normalized INTEGER,
    smart_255_raw INTEGER
    );
