# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to perform one iteration of the Kalman filter in parallel
#' @export
gen_kalman_filter_cpp <- function(a_0, Q_0, Q, F_, risk_sets, I_len, d, X, start, stop, events, order_) {
    .Call('dynamichazard_gen_kalman_filter_cpp', PACKAGE = 'dynamichazard', a_0, Q_0, Q, F_, risk_sets, I_len, d, X, start, stop, events, order_)
}

