# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chol_rank_one_update <- function(R, x) {
    invisible(.Call('dynamichazard_chol_rank_one_update', PACKAGE = 'dynamichazard', R, x))
}

square_tri_inv <- function(R, out) {
    invisible(.Call('dynamichazard_square_tri_inv', PACKAGE = 'dynamichazard', R, out))
}

symmetric_mat_chol <- function(A, out) {
    invisible(.Call('dynamichazard_symmetric_mat_chol', PACKAGE = 'dynamichazard', A, out))
}

tri_mat_times_vec <- function(A, x, out, is_transpose) {
    invisible(.Call('dynamichazard_tri_mat_times_vec', PACKAGE = 'dynamichazard', A, x, out, is_transpose))
}

sym_mat_rank_one_update <- function(alpha, x, A) {
    invisible(.Call('dynamichazard_sym_mat_rank_one_update', PACKAGE = 'dynamichazard', alpha, x, A))
}

bigglm_regcf_rcpp <- function(D, rbar, thetab, ss, checked, tol) {
    .Call('dynamichazard_bigglm_regcf_rcpp', PACKAGE = 'dynamichazard', D, rbar, thetab, ss, checked, tol)
}

IWLS_logit <- function(X, y, beta, offsets, it_max = 1e3L, eps = 1.0e-4) {
    .Call('dynamichazard_IWLS_logit', PACKAGE = 'dynamichazard', X, y, beta, offsets, it_max, eps)
}

IWLS_poisson <- function(X, y, beta, offsets, it_max = 1e3L, eps = 1.0e-4) {
    .Call('dynamichazard_IWLS_poisson', PACKAGE = 'dynamichazard', X, y, beta, offsets, it_max, eps)
}

ddhazard_fit_cpp <- function(X, fixed_terms, weights, tstart, tstop, a_0, fixed_parems_start, Q_0, Q, risk_obj, F_, eps_fixed_parems, max_it_fixed_params, n_max = 100L, eps = 0.001, verbose = 0L, order_ = 1L, est_Q_0 = TRUE, method = "EKF", kappa = NULL, alpha = NULL, beta = NULL, NR_eps = NULL, LR = NULL, model = "logit", M_step_formulation = "Fahrmier94", fixed_effect_chunk_size = 2e4L, debug = FALSE, NR_it_max = 100L, n_threads = -1L, ridge_eps = .0001, n_fixed_terms_in_state_vec = 0L, use_pinv = FALSE, criteria = "delta_coef", posterior_version = "cholesky") {
    .Call('dynamichazard_ddhazard_fit_cpp', PACKAGE = 'dynamichazard', X, fixed_terms, weights, tstart, tstop, a_0, fixed_parems_start, Q_0, Q, risk_obj, F_, eps_fixed_parems, max_it_fixed_params, n_max, eps, verbose, order_, est_Q_0, method, kappa, alpha, beta, NR_eps, LR, model, M_step_formulation, fixed_effect_chunk_size, debug, NR_it_max, n_threads, ridge_eps, n_fixed_terms_in_state_vec, use_pinv, criteria, posterior_version)
}

bigglm_updateQR_rcpp <- function(D, rbar, thetab, ss, checked, tol, model, X, eta, offset, y, w) {
    invisible(.Call('dynamichazard_bigglm_updateQR_rcpp', PACKAGE = 'dynamichazard', D, rbar, thetab, ss, checked, tol, model, X, eta, offset, y, w))
}

Posterior_approx_hepler_logit_compute_length <- function(offset, coef1, coef2, w, y) {
    .Call('dynamichazard_Posterior_approx_hepler_logit_compute_length', PACKAGE = 'dynamichazard', offset, coef1, coef2, w, y)
}

Posterior_approx_hepler_logit_second_d <- function(c, offset) {
    .Call('dynamichazard_Posterior_approx_hepler_logit_second_d', PACKAGE = 'dynamichazard', c, offset)
}

Posterior_approx_hepler_exp_compute_length <- function(offset, coef1, coef2, w, y, length) {
    .Call('dynamichazard_Posterior_approx_hepler_exp_compute_length', PACKAGE = 'dynamichazard', offset, coef1, coef2, w, y, length)
}

Posterior_approx_hepler_exp_second_d <- function(c, offset, length) {
    .Call('dynamichazard_Posterior_approx_hepler_exp_second_d', PACKAGE = 'dynamichazard', c, offset, length)
}

logLike_cpp <- function(X, risk_obj, F, Q_0, Q, a_t_d_s, tstart, tstop, fixed_effects_offsets, order_ = 1L, model = "logit") {
    .Call('dynamichazard_logLike_cpp', PACKAGE = 'dynamichazard', X, risk_obj, F, Q_0, Q, a_t_d_s, tstart, tstop, fixed_effects_offsets, order_, model)
}

get_risk_obj_rcpp <- function(start, stop, event, by, start_order, max_T, order_by_id_and_rev_start, id, is_for_discrete_model = TRUE, event_times_in = NULL, min_start_in = NULL) {
    .Call('dynamichazard_get_risk_obj_rcpp', PACKAGE = 'dynamichazard', start, stop, event, by, start_order, max_T, order_by_id_and_rev_start, id, is_for_discrete_model, event_times_in, min_start_in)
}

